### ISSUE TITLE
Typo on Item Usage

### ISSUE THREAD

**Issue by ppurcell** [kdiale-nerdery/thegame_frontend#1]
"Too use to use an item!"

**Comment by kdiale-nerdery** [comment]
I *think* this was fixed late last night. Can you refresh your client and let me know if you still see the problem?

**Comment by ppurcell** [comment]
403 Forbidden

**Comment by kdiale-nerdery** [comment]
Had a bug with my deploy code. Should be good to go now. sorry about the hiccups.

**Comment by ppurcell** [comment]
Verified.
